package com.openreceiver.app

import android.app.Activity
import android.os.Bundle
import android.widget.TextView
import com.openreceiver.core.NativeBridge

class MainActivity : Activity(), NativeBridge.StateCallback {

    private lateinit var bridge: NativeBridge
    
    private lateinit var tvTitle: TextView
    private lateinit var tvArtist: TextView
    private lateinit var tvCurrentLyric: TextView

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        // R.layout.activity_main will be generated by AAPT during the build
        setContentView(resources.getIdentifier("activity_main", "layout", packageName))

        tvTitle = findViewById(resources.getIdentifier("tvTitle", "id", packageName))
        tvArtist = findViewById(resources.getIdentifier("tvArtist", "id", packageName))
        tvCurrentLyric = findViewById(resources.getIdentifier("tvCurrentLyric", "id", packageName))

        bridge = NativeBridge()
        bridge.setCallback(this)
        bridge.initCore()
    }

    override fun onDestroy() {
        super.onDestroy()
        bridge.shutdownCore()
    }

    override fun onTrackInfoChanged(title: String, artist: String, album: String, duration: Double) {
        // NativeBridge calls this on a background JNI thread; we must marshal to main UI thread
        runOnUiThread {
            tvTitle.text = title
            tvArtist.text = artist
            // Clear lyrics display on track change
            tvCurrentLyric.text = ""
        }
    }

    override fun onPlaybackStateChanged(status: Int, position: Double) {
        runOnUiThread {
            // Update progress bar and sync lyrics in full implementation
        }
    }
}
